services:
  rpc_control:
    image: eth-mempool-monitor:latest
    container_name: rpc_control
    restart: unless-stopped
    depends_on:
      valkey:
        condition: service_healthy
    volumes:
      - ./config.toml:/config/config.toml:ro
    entrypoint:
      - /usr/local/bin/rpc_control
    command:
      - --config
      - /config/config.toml
      - --listen-host
      - 0.0.0.0
      - --redis-host
      - valkey
    ports:
      - "8080:8080"
    cpus: "0.50"
    mem_limit: 6m
    mem_reservation: 6m

  eth_mempool_monitor:
    image: eth-mempool-monitor:latest
    container_name: eth_mempool_monitor
    restart: unless-stopped
    depends_on:
      valkey:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
      rpc_control:
        condition: service_started
    volumes:
      - ./config.toml:/config/config.toml:ro
    command:
      - --config
      - /config/config.toml
      - --redis-host
      - valkey
      - --rabbitmq-host
      - rabbitmq
    cpus: "1.00"
    mem_limit: 6m
    mem_reservation: 6m

  valkey:
    image: valkey/valkey:latest
    container_name: valkey
    ports:
      - "6379:6379"
    ulimits:
      nofile:
        soft: 262144
        hard: 262144
    sysctls:
      net.core.somaxconn: "65535"
    command:
      - valkey-server
      - --save
      - ""
      - --appendonly
      - "no"
      - --io-threads
      - "4"
      - --io-threads-do-reads
      - "yes"
      - --tcp-backlog
      - "65535"
      - --lazyfree-lazy-user-del
      - "yes"
    healthcheck:
      test: ["CMD", "valkey-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 20
      start_period: 5s
    cpus: "1.00"
    mem_limit: 20m
    mem_reservation: 20m

  rabbitmq:
    image: rabbitmq:3
    container_name: rabbitmq
    hostname: rabbitmq
    environment:
      RABBITMQ_NODENAME: rabbit@rabbitmq
      RABBITMQ_SERVER_ADDITIONAL_ERL_ARGS: -os_mon start_disksup false
    ports:
      - "5672:5672"
    ulimits:
      nofile:
        soft: 262144
        hard: 262144
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq
      - ./rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf:ro
      - ./rabbitmq-advanced.config:/etc/rabbitmq/advanced.config:ro
    command:
      - /bin/sh
      - -ec
      - |
        rabbitmq-plugins disable --offline rabbitmq_federation rabbitmq_prometheus rabbitmq_web_dispatch
        exec rabbitmq-server
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "-q", "ping"]
      interval: 10s
      timeout: 5s
      retries: 20
      start_period: 10s
    cpus: "1.50"
    mem_limit: 256m
    mem_reservation: 256m

volumes:
  rabbitmq-data:
